Hai un DataFrame che rappresenta un elenco di studenti con i seguenti dati:

Nome (stringa): il nome dello studente.
Età (int): l'età dello studente.
Classe (stringa): la classe frequentata (es. "3A", "2B", ecc.).
Media_Voti (float): la media dei voti dello studente.
Partecipazione (bool): indica se lo studente ha partecipato ad almeno il 75% delle  lezioni (True/False).

1 - Filtro con AND: Estrai tutti gli studenti che hanno una media voti maggiore o uguale a 7 e un'età maggiore o uguale a 18.

2 - Filtro con OR: Estrai tutti gli studenti che appartengono alla classe "3A" oppure hanno una media voti superiore a 8.

3 - Filtro con NOT: Estrai tutti gli studenti che non hanno partecipato ad almeno il 75% delle lezioni.

4 - Filtro combinato (AND, OR e NOT): Estrai tutti gli studenti che:
    - Sono nella classe "2B" e hanno una media voti inferiore a 6;
    - Oppure che hanno più di 20 anni ma non hanno partecipato ad almeno il 75% delle lezioni.

In [1]:
import numpy as np
import pandas as pd

url_csv = 'studenti.csv'
size = 50
classi = ['3A', '2B', '1D', '1A', '2C', '3D', '1B', '3C']
nomi = ['Luca', 'Anna', 'Marco', 'Giulia', 'Paolo', 'Maria', 'Frank', 'Anastasia']

np.random.seed(42)

# Genero N(size) numeri casuali dal 15 al 25
numEta = np.random.randint(15, 25, size)
# print(numEta)
# Genero N(Size) valori casuali presi nell'array calssi
randClassi = np.random.choice(classi, size)
# print(randClassi)
randNomi = np.random.choice(nomi, size)
# print(randNomi)
# random.uniform genera N(size) numeri di tipo float casuali da 4 a 10
# round arrotonda il valore float al numeri intero più vicino, 
# il secondo valore(1) indica il numero di decimali da restituire dopo la virgola
randMedia = np.round(np.random.uniform(4, 10, size), 1)
# print(randMedia)

# Dizionario con dati di esempio generati con il metodo random
data = {
    'Nome': randNomi,
    'Eta': numEta,
    'Classe': randClassi,
    'Media_Voti': randMedia,
    'Partecipazione': np.random.choice([True, False], size)
}

# Genero un DataFrame da un Dizionario
studenti = pd.DataFrame(data)
# Salvo i dati su un file studenti.csv
studenti.to_csv(url_csv)

In [8]:
import pandas as pd

url_csv = 'studenti.csv'

# Leggo i dati da un CSV e genero un DataFrame con Pandas
studenti = pd.read_csv( url_csv, encoding='ISO-8859-1' )

#1 - Filtro con AND: Estrai tutti gli studenti che hanno una media voti 
# maggiore o uguale a 7 e un'età maggiore o uguale a 18.

filtro1 = (studenti.Media_Voti >= 7) & (studenti.Eta >= 18)
soluzione1 = studenti[filtro1]

# 2 - Filtro con OR: Estrai tutti gli studenti che appartengono 
# alla classe "3A" oppure hanno una media voti superiore a 8.
filtro2 = (studenti.Classe == "3A") | (studenti.Media_Voti > 8)
soluzione2 = studenti[filtro2]

# 3 - Filtro con NOT: Estrai tutti gli studenti che non 
# hanno partecipato ad almeno il 75% delle lezioni.
filtro3 = ~studenti.Partecipazione
soluzione3 = studenti[filtro3]

# 4 - Filtro combinato (AND, OR e NOT): Estrai tutti gli studenti che:
#    - Sono nella classe "2B" e hanno una media voti inferiore a 6;
#    - Oppure che hanno più di 20 anni ma non hanno partecipato ad almeno il 75% delle lezioni.
filtro4 = ((studenti.Classe == "2B") & (studenti.Media_Voti <6)) | ((studenti.Eta > 20)) & (~studenti.Partecipazione)
soluzione4 = studenti[filtro4]

soluzione4

    Unnamed: 0       Nome  Eta Classe  Media_Voti  Partecipazione
0            0      Frank   21     1B         8.6           False
5            5       Luca   24     2B         6.6           False
8            8     Giulia   22     2B         4.2            True
11          11      Frank   22     3D         7.1           False
12          12      Marco   22     2B         9.4           False
17          17      Marco   22     2B         4.5            True
18          18       Luca   20     2B         5.7            True
22          22      Frank   24     3D         7.8           False
24          24       Luca   23     3D         8.8           False
26          26      Frank   24     3C         9.4           False
28          28  Anastasia   21     3C         8.8           False
36          36  Anastasia   23     3C         4.0           False
40          40  Anastasia   23     2C         4.7           False
44          44       Luca   24     1A         7.1           False
48          48      Maria   21     3A         9.8           False